runtime: php81

handlers:
# Serve a directory as a static resource.
- url: /stylesheet
  static_dir: stylesheet

- url: /javascript
  static_dir: javascript

 #Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

#Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

